DominicanPingPong/Models/ErrorViewModel.cs
namespace DominicanPingPong.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DominicanPingPong/Models/PlayerModel.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DominicanPingPong.Models
{
    public class PlayerModel
    {
        [Key]
        [DatabaseGenerated (DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public string Position { get; set; }

        public string HandPosition { get; set; }

        public int Wins { get; set; }



    }
}

DominicanPingPong/Models/PlayerViewModel.cs
namespace DominicanPingPong.Models
{
    public class PlayerViewModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public string Position { get; set; }

        public string HandPosition { get; set; }

        public int Wins { get; set; }
    }
}

DominicanPingPong/Controllers/HomeController.cs
using DominicanPingPong.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DominicanPingPong.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DominicanPingPong/Controllers/PlayersController.cs
using DominicanPingPong.Data;
using DominicanPingPong.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DominicanPingPong.Controllers
{
    public class PlayersController : Controller
    {
        private readonly DominicanDbContext DominicanDbContext;

        public PlayersController(DominicanDbContext DominicanDbContext)
        {
            this.DominicanDbContext = DominicanDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var players = await DominicanDbContext.Players.ToListAsync();
            return View(players);
        }

        public IActionResult AddPlayer()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddPlayer(PlayerViewModel playerViewModel)
        {
            var player = new PlayerModel()
            {
                FirstName = playerViewModel.FirstName,
                LastName = playerViewModel.LastName,
                Position = playerViewModel.Position,
                HandPosition = playerViewModel.HandPosition,
                Wins = playerViewModel.Wins
            };

            await DominicanDbContext.Players.AddAsync(player);
            await DominicanDbContext.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var player = await DominicanDbContext.Players.FirstOrDefaultAsync(x => x.Id == id);
            return View(player);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var player = await DominicanDbContext.Players.FirstOrDefaultAsync(x => x.Id == id);

            return View(player);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PlayerModel playerModel)
        {
            var player = await DominicanDbContext.Players.FirstOrDefaultAsync(x => x.Id == playerModel.Id);
            if (player != null)
            {
                player.FirstName = playerModel.FirstName;
                player.LastName = playerModel.LastName;
                player.Position = playerModel.Position;
                player.HandPosition = playerModel.HandPosition;
                player.Wins = playerModel.Wins;
                await DominicanDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                return View("Index");
            }
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var player = await DominicanDbContext.Players.FirstOrDefaultAsync(x => x.Id == id);
            return View(player);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(PlayerModel employeeModel)
        {
            var player = await DominicanDbContext.Players.FirstOrDefaultAsync(x => x.Id == employeeModel.Id);
            if (player != null)
            {
                DominicanDbContext.Players.Remove(player);
                await DominicanDbContext.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View("Index");
        }

    }
}

DominicanPingPong/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To DU Ping Pong!</h1>
    <p>Welcome to the official page of the Dominican University Men's Ping Pong Team. You're home for rosters, records,and reports!</a>.</p>

        <img src="https://www.marketplace.org/wp-content/uploads/2020/07/GettyImages-1248502207.jpg?fit=2880%2C1620" alt="Description of the image" width="1000" height="800">

</div>

DominicanPingPong/Views/Players/AddPlayer.cshtml
@model DominicanPingPong.Models.PlayerModel

@{
    ViewData["Title"] = "AddPlayer";
}

<h1>AddPlayer</h1>

<h4>PlayerModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPlayer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HandPosition" class="control-label"></label>
                <input asp-for="HandPosition" class="form-control" />
                <span asp-validation-for="HandPosition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wins" class="control-label"></label>
                <input asp-for="Wins" class="form-control" />
                <span asp-validation-for="Wins" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DominicanPingPong/Views/Players/Delete.cshtml
@model DominicanPingPong.Models.PlayerModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PlayerModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HandPosition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HandPosition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wins)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wins)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DominicanPingPong/Views/Players/Details.cshtml
@model DominicanPingPong.Models.PlayerModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PlayerModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HandPosition)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HandPosition)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Wins)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Wins)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DominicanPingPong/Views/Players/Edit.cshtml
@model DominicanPingPong.Models.PlayerModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PlayerModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HandPosition" class="control-label"></label>
                <input asp-for="HandPosition" class="form-control" />
                <span asp-validation-for="HandPosition" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wins" class="control-label"></label>
                <input asp-for="Wins" class="form-control" />
                <span asp-validation-for="Wins" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DominicanPingPong/Views/Players/Index.cshtml
@model IEnumerable<DominicanPingPong.Models.PlayerModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Roster</h1>

<p>
    <a asp-action="AddPlayer">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HandPosition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Wins)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HandPosition)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Wins)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DominicanPingPong/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DominicanPingPong</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DominicanPingPong.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DominicanPingPong</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Results</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Players" asp-action="Index">Roster</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DominicanPingPong - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>